apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    app: db-pvc
spec:
  storageClassName: hiops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi